name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/seqKAN
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel poetry

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Automatically Bump Patch Version
        run: |
          poetry version patch  # Increments the patch version
          NEW_VERSION=$(poetry version --short)
          echo "New version: $NEW_VERSION"
          # Commit & push the updated version
          git checkout main
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "Bump version to $NEW_VERSION [skip ci]"
          git push origin main
        
      - name: Build package
        run: |
          python3 -m poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
